### ISSUE TITLE
Inverted colors in app switcher thumbnails

### ISSUE THREAD

**Issue by arpio23** [cutie-shell/cutie-home#1]
Not sure this might be an issue in qt6-screencopy?

But most or maybe all non qml apps have red and blue inverted in app switcher. Noticed with Telegram-Desktop and Chromium

**Comment by erikinkinen** [comment]
Fixed by:
- https://github.com/cutie-shell/cutie-wlc/commit/24f4995402d5d7297b78d8957a31cdb0b329d3ca
- https://github.com/cutie-shell/qt6-screencopy/commit/becf2a9d9098259464d3dfff7dd0200278c0c686
